import time


class RequestTimeMiddleware:

    def __init__(self, get_response):
        """
        Initializes a new instance of the class.
        :param get_response: A callable object representing the next middleware in the chain.
        """
        self.get_response = get_response

    def __call__(self, request):
        """
        Middleware function to calculate the duration of a request.
        :param request: The incoming HTTP request.
        :return: The response generated by the view function.
        """
        timestamp = time.monotonic()

        response = self.get_response(request)

        print(
            f'* Request duration: {request.path} - '
            f'{time.monotonic() - timestamp:.3f} sec.'
        )
        return response
