# Generated by Django 5.0.2 on 2024-02-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_process', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='subject', to='education_process.subject', verbose_name='Teach subject'),
        ),
    ]
