# Generated by Django 5.0.2 on 2024-03-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_pupil_is_deleted_teacher_is_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
