# Generated by Django 5.0.1 on 2024-02-02 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_at_school', models.IntegerField(choices=[('3', '3'), ('7', '7'), ('8', '8'), ('9', '9'), ('6', '6'), ('1', '1'), ('4', '4'), ('11', '11'), ('10', '10'), ('5', '5'), ('2', '2')])),
                ('branch', models.CharField(choices=[('C', 'C'), ('B', 'B'), ('D', 'D'), ('A', 'A'), ('E', 'E')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_process.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_process.grade')),
                ('pupil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.pupil')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_process.subject')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pupils', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.pupil')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_process.subject')),
            ],
        ),
    ]
