# Generated by Django 5.0.2 on 2024-02-15 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(verbose_name='Grade')),
                ('symbol', models.CharField(max_length=1, verbose_name='___ th grade')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'List of grades',
            },
        ),
        migrations.CreateModel(
            name='RatingItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Mark status')),
            ],
            options={
                'verbose_name': 'Mark status',
                'verbose_name_plural': 'List of marks status',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'List of school subjects',
            },
        ),
        migrations.CreateModel(
            name='PupilsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_group', models.DateField(verbose_name='Class creation date')),
                ('updated', models.DateField(auto_now=True, verbose_name='Update date')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Date of creation')),
                ('grade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Class', to='education_process.grade', verbose_name='Class name')),
            ],
            options={
                'verbose_name': 'Class of pupil',
                'verbose_name_plural': 'Class of pupils',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(choices=[(10, '10'), (9, '9'), (8, '8'), (7, '7'), (6, '6'), (5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], verbose_name='Mark')),
                ('created', models.DateField(verbose_name='Date of creation')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_process.pupilsgroup', verbose_name='Class name')),
            ],
            options={
                'verbose_name': 'Gradebook',
                'verbose_name_plural': 'Marks',
            },
        ),
    ]
