# Generated by Django 5.0.1 on 2024-02-13 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education_process', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='schoolchild',
            field=models.ForeignKey(limit_choices_to={'user_status': 'Schoolchild'}, on_delete=django.db.models.deletion.CASCADE, related_name='score_schoolchild', to=settings.AUTH_USER_MODEL, verbose_name='Schoolchild'),
        ),
        migrations.AddField(
            model_name='score',
            name='score_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_process.ratingitemstatus', verbose_name='Mark status'),
        ),
        migrations.AddField(
            model_name='score',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'user_status': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('schoolchild', 'lesson', 'created')},
        ),
    ]
