# Generated by Django 5.0.2 on 2024-02-15 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education_process', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='pupil',
            field=models.ForeignKey(limit_choices_to={'user_status': 'pupil'}, on_delete=django.db.models.deletion.CASCADE, related_name='score_pupil', to=settings.AUTH_USER_MODEL, verbose_name='Pupil'),
        ),
        migrations.AddField(
            model_name='score',
            name='score_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_process.ratingitemstatus', verbose_name='Mark status'),
        ),
        migrations.AddField(
            model_name='score',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'user_status': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Teacher'),
        ),
        migrations.AddField(
            model_name='score',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_process.subject', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='grade',
            name='subjects',
            field=models.ManyToManyField(related_name='grade', to='education_process.subject', verbose_name='List of school subjects in grade'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('pupil', 'subject', 'created')},
        ),
    ]
