# Generated by Django 5.0.1 on 2024-02-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='branch',
            field=models.CharField(choices=[('E', 'E'), ('C', 'C'), ('D', 'D'), ('A', 'A'), ('B', 'B')], max_length=1),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_at_school',
            field=models.IntegerField(choices=[('4', '4'), ('5', '5'), ('6', '6'), ('10', '10'), ('8', '8'), ('3', '3'), ('7', '7'), ('1', '1'), ('9', '9'), ('2', '2'), ('11', '11')]),
        ),
    ]
