# Generated by Django 5.0.1 on 2024-02-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_process', '0002_alter_grade_branch_alter_grade_grade_at_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='branch',
            field=models.CharField(choices=[('B', 'B'), ('D', 'D'), ('E', 'E'), ('C', 'C'), ('A', 'A')], max_length=2),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_at_school',
            field=models.IntegerField(choices=[('11', '11'), ('2', '2'), ('5', '5'), ('6', '6'), ('7', '7'), ('10', '10'), ('4', '4'), ('9', '9'), ('3', '3'), ('8', '8'), ('1', '1')], max_length=2),
        ),
    ]
