# Generated by Django 5.0.1 on 2024-02-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_process', '0003_alter_grade_branch_alter_grade_grade_at_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='branch',
            field=models.CharField(choices=[('E', 'E'), ('A', 'A'), ('C', 'C'), ('B', 'B'), ('D', 'D')], max_length=2),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_at_school',
            field=models.CharField(choices=[('9', '9'), ('7', '7'), ('10', '10'), ('4', '4'), ('1', '1'), ('3', '3'), ('6', '6'), ('8', '8'), ('11', '11'), ('5', '5'), ('2', '2')], max_length=2),
        ),
    ]
